name: card_matching_game
description: A card-matching game with animation and state management.

# Specifies the Dart SDK version constraints
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Adding the provider package for state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The assets section includes image assets used in the app
  assets:
    - assets/card_back.png  # Path to the card back image used when cards are face-down

  # An optional section for fonts (commented out here)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Medium.ttf
