name: card_matching_game
description: A card-matching game with animation and state management.

# The following defines the Dart SDK version constraints
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Adding provider for state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The assets section allows you to add files to your app's assets directory.
  # Here we are including an image for the card back design.
  assets:
    - assets/card_back.png

  # An optional section for fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Medium.ttf
